require('lazy').setup({
  'tpope/vim-sleuth',
  'github/copilot.vim',
  require 'plugins/gitsigns',
  require 'plugins/which-key',
  require 'plugins/telescope',
  require 'plugins/lazydev',
  require 'plugins/lsp',
  require 'plugins/conform',
  require 'plugins/cmp',
  require 'plugins/onedark-theme',
  require 'plugins/todo-comments',
  require 'plugins/mini',
  require 'plugins/treesitter',
  require 'plugins/indent-blankline',
  require 'plugins/lint',
  require 'plugins/autopairs',
  require 'plugins/oil',
  require 'plugins/snacks',
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
