# Tap
tap "jamieweavis/tap"

# Formulae
brew "bash" # tokyonight tmux theme requires bash
brew "bat"
brew "diff-so-fancy"
brew "eza"
brew "fd" # for telescope.nvim
brew "fzf"
brew "gh"
brew "git"
brew "jamieweavis/tap/colstr"
brew "nvim"
brew "pnpm"
brew "ripgrep" # for telescope.nvim
brew "starship"
brew "stow"
brew "tmux"
brew "zsh"

# Casks
cask "1password"
cask "docker-desktop"
cask "figma"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "mac-mouse-fix"
cask "monitorcontrol"
cask "raycast"
cask "visual-studio-code"
