# 'brew install'
brew "awscli"
brew "bat"
brew "git"
brew "nethack"
brew "starship"
brew "stow"
brew "vim"
brew "zsh"

# 'brew install --cask'
cask "1password"
cask "ableton-live-suite"
cask "affinity-photo"
cask "arc"
cask "docker"
cask "figma"
cask "font-fira-code-nerd-font"
cask "font-fira-code"
cask "google-chrome"
cask "hyperkey"
cask "iterm2"
cask "mac-mouse-fix"
cask "raycast"
cask "spotify"
cask "visual-studio-code"
