# 'brew tap'
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# 'brew install'
brew "antigen"
brew "bat"
brew "deno"
brew "git"
brew "grc"
brew "mysql@5.7", restart_service: true, link: true, conflicts_with: ["mysql"]
brew "nvm"
brew "prettyping"
brew "koekeishiya/formulae/skhd"
brew "tree"
brew "vim"
brew "koekeishiya/formulae/yabai"
brew "yarn"
brew "zsh"

# 'brew cask install'
cask "1password"
cask "aerial"
cask "alfred"
cask "alt-tab"
cask "ballast"
cask "battle-net"
cask "brooklyn"
cask "discord"
#cask "dotnet-sdk"
cask "dozer"
cask "figma"
cask "font-hasklig"
cask "font-hasklug-nerd-font"
cask "google-backup-and-sync"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "keepingyouawake"
#cask "mono-mdk"
cask "postman"
cask "sequel-pro-nightly"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "ubersicht"
#cask "unity"
#cask "unity-hub"
cask "visual-studio-code"
