# 'brew install'
brew "awscli"
brew "bat"
brew "git"
brew "nethack"
brew "starship"
brew "stow"
brew "tmux"
brew "vim"
brew "zsh"

# 'brew install --cask'
cask "1password"
cask "ableton-live-suite"
cask "affinity-photo"
cask "ankerwork"
cask "battle-net"
cask "docker"
cask "figma"
cask "firefox"
cask "firefox@developer-edition"
cask "font-fira-code-nerd-font"
cask "font-fira-code"
cask "hyperkey"
cask "iterm2"
cask "mac-mouse-fix"
cask "monitorcontrol"
cask "protonvpn"
cask "raycast"
cask "spotify"
cask "steam"
cask "valhalla-freq-echo"
cask "valhalla-space-modulator"
cask "valhalla-supermassive"
cask "visual-studio-code"
