syntax on           " Enable syntax highlighting

set number          " Show line numbers
set nowrap          " Don't wrap lines
set scrolloff=5     " Keep 5 lines above/below when vertical scrolling
set sidescrolloff=5 " Keep 5 cols left/right when horizontal scolling

set showmatch       " Highlight matching braces
set hlsearch        " Highlight search matches
set incsearch       " Search as characters are entered
set ignorecase      " Ignore case of search

set wildmenu        " Visual tab autocomplete for : command menu
set ruler           " Show caret coordinates on status bar

set smarttab
set smartindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab       " Use spaces instead of tabs

set ai              " Auto indent
set si              " Smart indent
set wrap            " Wrap lines

set backspace=2     " Allow backspace at start of line
set nocompatible    " Fix insert mode?

set laststatus=2    " Show status line

