# Prompt segment order
format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

[time]
disabled = false
format = "[$time]($style) "

[character]
success_symbol = "[●](bold green)"
error_symbol = "[⭘](bold red)"
vimcmd_symbol = "[●](bold green)"

[directory]
read_only = " ro"
format = "in [$path]($style) "

[git_branch]
symbol = ""
